// Traduction FR des libellés de CATÉGORIES/SOUS-CATÉGORIES/RÔLES du catalogue.
// Ces valeurs viennent des données brutes (UEX /categories, ShipData.role) qui ne
// sont qu'en ANGLAIS. On les mappe ici pour l'affichage FR ; repli sur l'anglais si
// un terme n'est pas connu. La VALEUR (clé de filtre backend) reste l'anglais.

const CATALOG_FR: Record<string, string> = {
  // ── Sections (filtre principal) ──
  Armor: "Armures",
  Avionics: "Avionique",
  Clothing: "Vêtements",
  Commodities: "Marchandises",
  Consumable: "Consommables",
  Consumables: "Consommables",
  Data: "Données",
  Decorations: "Décorations",
  Flair: "Ornements",
  Liveries: "Livrées",
  Miscellaneous: "Divers",
  Module: "Modules",
  Other: "Autre",
  "Personal Weapons": "Armes personnelles",
  Propulsion: "Propulsion",
  Systems: "Systèmes",
  Technology: "Technologie",
  Undersuits: "Sous-combinaisons",
  Utility: "Utilitaire",
  "Vehicle Weapons": "Armes de vaisseau",
  Vehicles: "Vaisseaux",

  // ── Sous-catégories ──
  Arms: "Bras",
  Backpacks: "Sacs à dos",
  "Full Set": "Panoplie complète",
  Helmets: "Casques",
  Legs: "Jambières",
  Torso: "Torse",
  "Flight Blade": "Lame de vol",
  Radar: "Radar",
  Dresses: "Robes",
  Eyeware: "Lunettes",
  Footwear: "Chaussures",
  Gloves: "Gants",
  Hats: "Chapeaux",
  Jackets: "Vestes",
  Jumpsuits: "Combinaisons",
  Legwear: "Bas",
  Shirts: "Hauts",
  Harvestables: "Récoltables",
  Cards: "Cartes",
  "Points of Interest": "Points d'intérêt",
  Storage: "Stockage",
  Surface: "Surface",
  Container: "Conteneur",
  Drinks: "Boissons",
  Foods: "Nourriture",
  Attachments: "Accessoires",
  "Jump Modules": "Modules de saut",
  Batteries: "Batteries",
  Coolers: "Refroidisseurs",
  "Gravity Generator": "Générateur de gravité",
  "Life Support Generator": "Générateur de survie",
  "Power Plants": "Centrales électriques",
  "Quantum Drives": "Lecteurs quantiques",
  "Shield Generators": "Générateurs de bouclier",
  Mobiglas: "Mobiglas",
  "Docking Collars": "Colliers d'amarrage",
  "External Fuel Tanks": "Réservoirs externes",
  Fabricator: "Fabricateur",
  "Fuel Nozzle": "Buse de carburant",
  Gadgets: "Gadgets",
  "Mining Laser Heads": "Têtes de minage laser",
  "Mining Modules": "Modules de minage",
  "Salvage Beams": "Faisceaux de récupération",
  "Scraper Beams": "Faisceaux de grattage",
  "Tractor Beams": "Rayons tracteurs",
  "Bomb Racks": "Râteliers à bombes",
  Bombs: "Bombes",
  Guns: "Canons",
  "Missile Racks": "Râteliers à missiles",
  Missiles: "Missiles",
  "Point Defense Cannon": "Canon de défense rapprochée",
  "Torpedo Tubes": "Tubes lance-torpilles",
  Turrets: "Tourelles",

  // ── Rôles de vaisseaux (ShipData.role) — repli anglais si non mappé ──
  Cargo: "Fret",
  Transport: "Transport",
  Combat: "Combat",
  Fighter: "Chasseur",
  "Heavy Fighter": "Chasseur lourd",
  "Medium Fighter": "Chasseur moyen",
  "Light Fighter": "Chasseur léger",
  "Snub Fighter": "Chasseur d'appoint",
  Bomber: "Bombardier",
  Gunship: "Canonnière",
  Exploration: "Exploration",
  Expedition: "Expédition",
  Pathfinder: "Éclaireur",
  Mining: "Minage",
  Medical: "Médical",
  Salvage: "Récupération",
  Refuel: "Ravitaillement",
  Repair: "Réparation",
  Racing: "Course",
  Touring: "Tourisme",
  "Multi-Role": "Polyvalent",
  Interdiction: "Interdiction",
  Passenger: "Passagers",
  Industrial: "Industriel",
  Stealth: "Furtif",
  Support: "Soutien",
  Ground: "Terrestre",
  Construction: "Construction",
  Dropship: "Transport de troupes",
  Starter: "Débutant",
  Competition: "Compétition",
  Courier: "Coursier",
  Scanning: "Détection",
  Reporting: "Reconnaissance",
};

/** Traduit un libellé de catalogue en FR (repli anglais). `lang` = i18n.language. */
export function catLabel(value: string | null | undefined, lang: string): string {
  if (!value) return "";
  if (!lang.toLowerCase().startsWith("fr")) return value;
  return CATALOG_FR[value] ?? value;
}
